[[conn]]
type = "mysql"
user = "root"
host = "localhost"
database = "world"
port = 3306

[[conn]]
type = "mysql"
user = "root"
host = "localhost"
port = 3306

[[conn]]
type = "postgres"
user = "postgres"
host = "localhost"
port = 5432

[[conn]]
type = "postgres"
user = "postgres"
host = "localhost"
port = 5432
database = "dvdrental"

[[conn]]
type = "sqlite"
path = "/Users/tako8ki/Downloads/chinook.db"
